name: Update Coin Configs and create 128x128 images in icons dir

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'utils/coins_config.json'
      - 'utils/coins_config_ssl.json'
      - 'utils/coins_config_tcp.json'
      - 'utils/coins_config_wss.json'
  schedule:
    - cron:  '0 0 * * *'

jobs:
  update_configs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create 128x128 images in icons dir
        shell: bash
        run:  ${GITHUB_WORKSPACE}/utils/icons_resize.sh

      - name: Generate configs
        shell: bash
        run:  pip3 install websockets && ${GITHUB_WORKSPACE}/utils/generate_app_configs.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: update coins json file
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: json-config-update
          delete-branch: true
          title: '[BOT] Update coins config json'
          body: |
            - Coins JSON config auto-generated on merge to master
            - Electrum scan report updated
          labels: |
            config-update
          reviewers: cipig, smk762, gcharang
          draft: false
